<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form action="/students/update/{{ $data->id }}" class="form" method="POST">
                <div class="form-group">
                    <input type="hidden" name="id" value="{{ $data->id }}">
                    <input type="text" name="name" class="form-control" placeholder="Name" value="{{ $data->name }}">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</div>