<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form action="/students/form" class="form" method="POST">
                <div class="form-group">
                    @if($post->id)
                    <input type="hidden" name="id" value="{{ $post->id }}">
                    @endif

                    <input type="text" name="name" class="form-control" placeholder="Name" value="{{ $post->name }}">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</div>