
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-primary" href="/students/form">Tambah</a>
            <table class="table">
                <tr>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
                @if($data)
                @foreach($data as $students)
                <tr>
                    <td>{{ $students->name }}</td>
                    <td>
                        <a href="/students/form/{{$students->id}}">Edit</a>
                        <a href="/students/delete/{{$students->id}}">Hapus</a>
                    </td>
                </tr>
                @endforeach
                @endif
            </table>
        </div>
    </div>
</div>