<?php
/**
 * Created by O2System Framework File Generator.
 * DateTime: 10/10/2019 11:10
 */

// ------------------------------------------------------------------------

namespace App\Controllers;

// ------------------------------------------------------------------------

use O2System\Framework\Http\Controller;

/**
 * Class Students
 *
 * @package \App\Controllers
 */
class Students extends Controller
{
    /**
     * Students::index
     */
    public function index()
    {
        // TODO: Change the autogenerated stub
    }
}